server:
  port: 8964

spring:
  thymeleaf:
    suffix: .html
  main:
    allow-bean-definition-overriding: true

  datasource:
    username: root
    password: bxy0516
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.81.78:3306/setraining?serverTimezone=GMT%2B8
#    username: bxy
#    password: bxy0516
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost;databaseName=setraining

  redis:
        host: 127.0.0.1
        # Redis服务器连接端口
        port: 6379
        jedis:
          pool:
            #连接池最大连接数（使用负值表示没有限制）
            max-active: 100
            # 连接池中的最小空闲连接
            max-idle: 10
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: 100000
        # 连接超时时间（毫秒）
        timeout: 5000
        #默认是索引为0的数据库
        database: 0

  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: 601789175@qq.com
    password: nstexbarhrhqbbgi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
