server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    username: root
    password: bxy0516
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/setraining?serverTimezone=GMT%2B8
